name: Publish Binaries

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete Existing Latest Tag and Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Delete the release first
        gh release delete latest --yes || true
        # Delete local tag
        git tag -d latest || true
        # Delete remote tag
        git push origin :refs/tags/latest || true
        # Create new tag at current commit
        git tag latest
        git push origin latest

    - name: Create New Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Find executable files in the root directory
        binaries=()
        for binary in *; do
          if [ -x "$binary" ] && [ -f "$binary" ]; then
            if [[ "$binary" != *.{yml,yaml,md,txt,json} ]] && [[ "$binary" != ".github" ]]; then
              binaries+=("$binary")
            fi
          fi
        done

        # Create new release with all binary files
        if [ ${#binaries[@]} -gt 0 ]; then
          gh release create latest "${binaries[@]}" \
            --title "Latest Binaries" \
            --notes "Automated release with all binary files" \
            --target main
        else
          echo "No binary files found to release"
        fi
