name: Publish Binaries

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete Existing Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Delete existing 'latest' release if it exists
        gh release delete latest -y || true

    - name: Create New Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Find executable files in the root directory
        binaries=()
        for binary in *; do
          # Check if file is executable and not a directory
          if [ -x "$binary" ] && [ -f "$binary" ]; then
            # Exclude workflow and typical non-binary files
            if [[ "$binary" != *.{yml,yaml,md,txt,json} ]] && [[ "$binary" != ".github" ]]; then
              binaries+=("$binary")
            fi
          fi
        done

        # Create new release with all binary files
        if [ ${#binaries[@]} -gt 0 ]; then
          gh release create latest "${binaries[@]}" \
            --generate-notes \
            --title "Latest Binaries" \
            --notes "Automated release with all binary files from the repository"
        else
          echo "No binary files found to release"
        fi
